// Code generated by MockGen. DO NOT EDIT.
// Source: internal/client/tweet/client.go
//
// Generated by this command:
//
//	mockgen -source=internal/client/tweet/client.go -destination=internal/client/tweet/mocks/mock_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	tweet "github.com/mdcantarini/twitter-clone/internal/client/tweet"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// FetchTweet mocks base method.
func (m *MockClient) FetchTweet(tweetID string) (*tweet.Tweet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchTweet", tweetID)
	ret0, _ := ret[0].(*tweet.Tweet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchTweet indicates an expected call of FetchTweet.
func (mr *MockClientMockRecorder) FetchTweet(tweetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchTweet", reflect.TypeOf((*MockClient)(nil).FetchTweet), tweetID)
}
